# if: tag IS present

language: python

env:
  global:
    - PORT=7000
    - entry=8000
    - DOCKER_REPO=acestream-service

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
  - pip install pytest-cov pytest-flake8 codecov

install:
  - docker run -d -e PORT=$PORT -e entry=$entry -p $entry:$PORT $DOCKER_USERNAME/$DOCKER_REPO

script:
  - sleep 2; python -m pytest
  - git clean -fd

deploy:
  - provider: script
    script: ./deploy.sh
    on:
      all_branches: true
