name: main

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPO: acestream-service
  PORT: 7000
  ENTRY: 8000

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: GITHUB_REF
        run: echo GITHUB_REF=$GITHUB_REF github.event.inputs.acestream=${{ github.event.inputs.acestream }}
      - name: build
        run: docker build -t $DOCKER_USERNAME/$DOCKER_REPO .
      - name: install
        run: pip install pytest-cov flake8 codecov
      - name: run
        run: docker run -d -e PORT=$PORT -e ENTRY=$ENTRY -p $ENTRY:$PORT $DOCKER_USERNAME/$DOCKER_REPO
      - name: sleep
        run: sleep 4
      - name: test
        run: |
          python -m pytest
          flake8 *.py
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' &&
                github.event.inputs.debug_enabled ||
                failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: deploy
        if: ${{ startsWith(github.ref, 'refs/tags/')
        env:
          TAG: ${{ github.ref_name }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          HEROKU: ${{ secrets.HEROKU }}
        run: ./deploy.sh
